on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - run: mkdir -p .pki/nssdb

      - name: Test Creating NSS DB
        id: test-action
        uses: ./
        with:
          cmd: certutil -d sql:.pki/nssdb -N --empty-password

      - name: Ensure file exists and readable
        run: |
          ls -la .pki/nssdb
          test -f .pki/nssdb/pkcs11.txt
          cat .pki/nssdb/pkcs11.txt > /dev/null
